export const DASHBOARD_CAPTURE_DEVICE_SCALE_FACTOR = 2;
export const DASHBOARD_CAPTURE_VIEWPORT_WIDTH = 1280;
export const DASHBOARD_CAPTURE_VIEWPORT_HEIGHT = 1100;
export const DASHBOARD_CAPTURE_CLIP_PADDING = 24;
export const DASHBOARD_CAPTURE_CLIP_WIDTH = 1100;
export const DASHBOARD_CAPTURE_PAGE_WIDTH =
  DASHBOARD_CAPTURE_CLIP_WIDTH - (DASHBOARD_CAPTURE_CLIP_PADDING * 2);
